title: "Taskify"
remote_theme: pmarsceill/just-the-docs

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: GFM

repository: "AY2021S2-CS2103T-W14-4/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
